#!/bin/sh
export_ () { export $1=$2; }

export_ PYTHONPATH  ${PWD}
export_ out         ${PWD}/build.out
export_ target      ${out}/eating.tmp
export_ sh   ${out}/main.sh
export_ py   ${PWD}/eman/generate_script.py

mkdir -p ${out}

[ "$1" == "-f" ] && rm -rf ${target}
[ -e ${target} ] && echo Remove ${target} first or use [-f]. && exit

echo BUILDING AT ${target}
pushd ${out} > /dev/null
${py} > ${sh}
chmod +x ${sh}
${sh}
popd > /dev/null
