#!/usr/bin/env python3

import eman as EMAN

BUILD=EMAN.ROOT/'build.out'
BUILD.mkdir(exist_ok=True)

def main():
    for index in sorted(EMAN.INDEX.glob('*')):
        download_index(index)
        assemble_index(index)


def download_index(index):
    enum = EMAN.EnumeratedSequence( EMAN.urls4file(index) )
    enum.cb_first = lambda e : None
    enum.cb_next  = lambda e : EMAN.back( f'{index.name}: {e.ii()}/{e.total()}')
    enum.cb_last  = lambda e : EMAN.back( '\n')
    for ii,url in enum.withself():
        iname = index.name
        fname = f'{iname}.{EMAN.pad(ii)}.mp4'
        dst = BUILD/iname/fname
        EMAN.wget(url, dst)

def assemble_index(index):
    pass



if __name__ == '__main__':
    main()



